### ISSUE TITLE
Seems need to add at least one in arguments of createContext()

### ISSUE THREAD

**Issue by c1495616js** [jared-jewitt/portable-react-boilerplate#7]
Thanks for providing this awesome boilerplate.
I just try to implement auth-context and found that seems need to add something in arguments, 
like `createContext(null, or defaultValue)`
it will show error if I just use `createContext()`

in file `auth-provider.js`
```
export const AuthContext = createContext();
```

**Comment by jared-jewitt** [comment]
Thanks for the feedback @c1495616js :)

Could you send a screenshot of the error you're seeing? I can build the app locally and use the provider with no problems. React docs state this value is optional.

https://reactjs.org/docs/context.html#api
